spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/smart_classroom?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.example.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


server:
  port: 8088

logging:
  level:
    org.springframework.web: DEBUG